name: My hovercraft is full of eels
markdown: kramdown
highlighter: rogue
permalink: /blog/:year/:month/:day/:title/
timezone: Australia/Melbourne
author: Simon Harris
url: http://www.harukizaemon.com
